testing expand

diff --git a/src/orb.yml b/src/orb.yml
--- a/src/orb.yml
+++ b/src/orb.yml
@@ -53,7 +53,7 @@ commands:
             cd scantemp
             
             cat \<< 'EOF' > ./scan.sh
-            
+
             #!/bin/bash
             set -euo pipefail
             MICROSCANNER_TOKEN="${MICROSCANNER_TOKEN:-}"
@@ -63,63 +63,68 @@ commands:
             MICROSCANNER_SOURCE="https://get.aquasec.com/microscanner"
 
             main() {
-            local MICROSCANNER_SOURCE
-            [[ -z ${MICROSCANNER_TOKEN} ]] && {
-              print_usage
-              exit 1
-            }
-            [[ -z ${DOCKER_IMAGE} ]] && {
-              print_usage
-              exit 1
-            }
+              local MICROSCANNER_SOURCE
+              [[ -z ${MICROSCANNER_TOKEN} ]] && {
+                print_usage
+                exit 1
+              }
+              [[ -z ${DOCKER_IMAGE} ]] && {
+                print_usage
+                exit 1
+              }
 
-            trap cleanup EXIT
+              trap cleanup EXIT
 
-            TEMP_DIR=$(mktemp -d)
-            cd "${TEMP_DIR}"
+              TEMP_DIR=$(mktemp -d)
+              cd "${TEMP_DIR}"
 
-            {
-              echo "FROM ${DOCKER_IMAGE}"
+              {
+                echo "FROM ${DOCKER_IMAGE}"
 
-              cat \<<'EOL'
-            RUN if [ ! -d /etc/ssl/certs/ ] || { [ ! -f /etc/ssl/certs/ca-certificates.crt ] && [ ! -f /etc/ssl/certs/ca-bundle.crt ]; }; then \
-            PACKAGE_MANAGER=$(basename \
-              $({ command -v apk apt yum false 2>/dev/null || which apk apt yum false; } \
-              | head -n1)); \
-            if [ "${PACKAGE_MANAGER}" = "apk" ]; then \
-              apk --update add ca-certificates; \
-            elif [ "${PACKAGE_MANAGER}" = "apt" ]; then \
-              apt update \
-                && apt install --no-install-recommends -y ca-certificates \
-                && update-ca-certificates; \
-            elif [ "${PACKAGE_MANAGER}" = "yum" ]; then \
-              yum install -y ca-certificates; \
-            else \
-              echo 'ca-certificates not found and package manager not apk, apt, or yum. Aborting' >&2; \
-              exit 1; \
-            fi; \
-            fi;
-            EOL
+                  cat \<<'EOL'
+              RUN if [ ! -d /etc/ssl/certs/ ] || { [ ! -f /etc/ssl/certs/ca-certificates.crt ] && [ ! -f /etc/ssl/certs/ca-bundle.crt ]; }; then \
+                PACKAGE_MANAGER=$(basename \
+                  $({ command -v apk apt yum false 2>/dev/null || which apk apt yum false; } \
+                  | head -n1)); \
+                if [ "${PACKAGE_MANAGER}" = "apk" ]; then \
+                  apk --update add ca-certificates; \
+                elif [ "${PACKAGE_MANAGER}" = "apt" ]; then \
+                  apt update \
+                    && apt install --no-install-recommends -y ca-certificates \
+                    && update-ca-certificates; \
+                elif [ "${PACKAGE_MANAGER}" = "yum" ]; then \
+                  yum install -y ca-certificates; \
+                else \
+                  echo 'ca-certificates not found and package manager not apk, apt, or yum. Aborting' >&2; \
+                  exit 1; \
+                fi; \
+              fi;
+              EOL
 
-              cat \<<EOL
-            ADD ${MICROSCANNER_SOURCE} /tmp/microscanner
-            USER root
-            RUN [ -x /tmp/microscanner ] || chmod +x /tmp/microscanner \
-            && sync \
-            && /tmp/microscanner --version \
-            && /tmp/microscanner ${MICROSCANNER_OPTIONS} ${MICROSCANNER_TOKEN}
-            EOL
+                  cat \<<EOL
+              ADD ${MICROSCANNER_SOURCE} /tmp/microscanner
+              USER root
+              RUN [ -x /tmp/microscanner ] || chmod +x /tmp/microscanner \
+                && sync \
+                && /tmp/microscanner --version \
+                && /tmp/microscanner ${MICROSCANNER_OPTIONS} ${MICROSCANNER_TOKEN}
+              EOL
 
-            } | docker build --force-rm -t ${TEMP_IMAGE_TAG} -f - .
-            }
-            cleanup() {
-            if docker inspect --type=image "${TEMP_IMAGE_TAG}" &>/dev/null; then
-              docker image rm --force "${TEMP_IMAGE_TAG}" || true
-            fi
-            rm -rf "${TEMP_DIR}" || true
-            }
+              } | docker build --force-rm -t ${TEMP_IMAGE_TAG} -f - .
+              }
+            
+              print_usage() {
+                echo "Usage: MICROSCANNER_TOKEN=xxxxxxxxxxxxxxxx ./scan.sh DOCKER_IMAGE"
+              }
+            
+              cleanup() {
+                if docker inspect --type=image "${TEMP_IMAGE_TAG}" &>/dev/null; then
+                  docker image rm --force "${TEMP_IMAGE_TAG}" || true
+                fi
+                rm -rf "${TEMP_DIR}" || true
+              }
 
-            main
+              main
             EOF
             chmod +x ./scan.sh
   scan:
